spring.application.name=exerciceAPI
spring.main.banner-mode=off
logging.level.org.springframework=ERROR

spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=jdbc:postgresql://localhost:5432/exercise_app
spring.datasource.username=postgres
spring.datasource.password=****

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# JWT Configuration
jwt.secret=PjucO8eWuGUPEPNQTqSTyoaTtYTj63kleurVnur0eMU=
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000